
* MLI call codes:

alloc     = $40
dealloc   = $41
quit      = $65
readblk   = $80
writeblk  = $81
gettime   = $82
create    = $C0
destroy   = $C1
rename    = $C2
setinfo   = $C3
getinfo   = $C4
online    = $C5
setpfix   = $C6
getpfix   = $C7
open      = $C8
newline   = $C9
read      = $CA
write     = $CB
close     = $CC
flush     = $CD
setmark   = $CE
getmark   = $CF
seteof    = $D0
geteof    = $D1
setbuf    = $D2
getbuf    = $D3
